[package]
name = "linoleum"
version = "3.0.1"
edition = "2021"

license = "MIT"
authors = ["Kyllingene"]
description = "A simple but ergonomic line editor."
repository = "https://github.com/Kyllingene/linoleum"

[dependencies]
antsy = "1.0.0"
crossterm = "0.27"

