[package]
name = "linoleum"
version = "2.2.0"
edition = "2021"

license = "MIT"
authors = ["Kyllingene"]
description = "A simple but ergonomic line editor."
repository = "https://github.com/Kyllingene/linoleum"

[dependencies]
crossterm = "0.27"

